"""
Quality Dimension (QD) check prompts ported from Code.gs.

Each function returns (system_prompt, rubric) for a specific QD.
The base_reviewer builds the user content by injecting task file contents.

QD Mapping:
  A  → Instruction quality (humane prompt, file validation, malpractice, consistency, typos)
  B  → Tests quality (docstrings, humane validation, forbidden patterns, brittle tests)
  C  → Slug & naming descriptiveness
  E  → Dockerfile validation (references, pinning, test deps, base image)
  F  → test.sh conformance
  G  → solve.sh validity (meaningful computation, no hardcoding, no leakage)
  H  → task.toml metadata completeness
  J  → Forced gates / model gating detection
  K1 → Failure analysis (worst model run)
  K2 → Cheating analysis (best model run)
  M  → Instruction-test alignment (bidirectional coverage)
"""

SYSTEM_HEADER = (
    "You are a senior technical reviewer for Terminal-Bench tasks. "
    "Terminal-Bench evaluates AI agents on real-world terminal tasks executed in sandboxed Docker environments. "
    "Its Harness manages setup, orchestration, and result parsing (via TrialHandler and ParserFactory which only support Pytest format); "
    "the Agent handles decision-making, terminal interaction, and command execution. "
    "Your job is to perform static analysis only — do not execute or assume runtime behavior. "
    "Rely exclusively on the provided text and file contents. "
    "Assess correctness, compliance with the Terminal-Bench architecture, clarity of instruction, "
    "test integrity, and consistency between the task, solution, and test logic. "
    "Be conservative in judgment: if uncertain, explicitly state the doubt. "
    "Focus on whether the task would run successfully under the Harness flow. "
    "Highlight any deviations from expected conventions, missing dependencies, unclear success criteria, "
    "or potential parser/test mismatches. "
    "BE STRAIGHT TO THE ISSUE AND FLAG IT. "
    "Output your response as valid JSON with the keys: score (PASS / PASS_WITH_WARNING / FAIL), "
    "issues (array of strings), and summary (one sentence)."
)

# ── QD-A: Instruction Quality ──────────────────────────────────────────────

QD_A_RUBRIC = r"""
A) PROMPT (instruction.md) — HUMANE PROMPT VALIDATION
Goal: Verify the prompt is written in HUMANE style AND all referenced input files exist.

PART 1: HUMANE PROMPT STYLE CHECK (CRITICAL)
Evaluate if the instruction.md is written like a HUMAN would naturally write it.

HUMANE PROMPT CHARACTERISTICS (should have MOST of these):
- Natural, conversational language
- Describes the GOAL/WHAT, not step-by-step HOW
- Uses context and background to explain the problem
- Allows flexibility in implementation approach
- Reads like a message from a colleague, not a spec document

NON-HUMANE (ROBOTIC) — should NOT have:
- Numbered step-by-step instructions like a checklist
- Overly formal, specification-style language
- Explicit function signatures or class definitions to implement
- Exact variable names/file paths the solution MUST use
- Template-style placeholders

TOO TERSE / CRYPTIC — should NOT have:
- Fewer than ~8-10 lines of meaningful content
- Reads like compressed shorthand or abbreviated notes
- Missing context about WHY the task exists or WHAT the problem domain is
- No explanation of input data, expected output, or success criteria
- Omits output file names or key requirements that tests later check for

LLM-GENERATED FORMATTING — FAIL if excessive:
- Too many markdown headers everywhere
- Excessive bullet point lists for everything
- Bold/italic on every other word
- Over-structured like documentation, not natural speech

PART 2: ENVIRONMENT FILE VALIDATION
For each file/path mentioned in instruction.md that the agent needs to READ:
- Check if it exists in the environment files list
- Check if it is generated by Dockerfile
- Output files (agent creates them) are OK if not present

PART 3: MALPRACTICE CHECK
- Model-specific language in instruction.md CONTENT (NOT model-run-logs paths) -> FAIL
- PII (real names, emails) -> FLAG
- References to solve.sh or solution/ -> FAIL

PART 4: INTERNAL CONSISTENCY CHECK (CRITICAL)
Scan for INTERNAL CONTRADICTIONS:
- Numeric precision conflicts
- File path/name conflicts
- Format conflicts
- Value/parameter conflicts
- Requirement conflicts

PART 5: TYPOS CHECK
Cross-check between instruction.md, test file, and solve.sh for:
- File name mismatches
- Variable/key name mismatches
- Path name mismatches (case sensitivity)

OUTPUT FORMAT (JSON):
{
  "score": "PASS" | "PASS_WITH_WARNING" | "FAIL",
  "humane_style": {"verdict": "...", "reasoning": "..."},
  "file_validation": {"verdict": "...", "missing_files": []},
  "malpractice": {"verdict": "...", "findings": []},
  "consistency": {"verdict": "...", "contradictions": []},
  "typos": {"verdict": "...", "findings": []},
  "issues": ["list of all issues found"],
  "summary": "one sentence summary"
}
"""


# ── QD-B: Tests Quality ───────────────────────────────────────────────────

QD_B_RUBRIC = r"""
B) TESTS (tests/test_outputs.py) — HUMANE PROMPT MODE
Goal: Tests verify the task's intent, allowing for IMPLIED requirements that experts would understand.

PART 1: INFORMATIVE TEST DOCSTRINGS (REQUIRED)
Every test function MUST have an informative docstring that:
1. Describes what behavior the test checks
2. References the corresponding requirement in instruction.md

FAILING DOCSTRING EXAMPLES:
- No docstring at all
- Generic docstring like "Test the output." or "Check results."
- Docstring that doesn't explain WHAT is being verified

DOCSTRING VERDICT:
- If ALL tests lack docstrings -> FAIL
- If >50% of tests lack informative docstrings -> WARNING
- If <=50% lack docstrings -> PASS

PART 2: HUMANE PROMPT VALIDATION
ACCEPT AS VALID (DO NOT FLAG):
- Tests checking data structures/formats standard for the domain
- Tests verifying numeric precision experts would expect
- Tests validating intermediate steps necessary for final output
- Any test checking something a competent developer would naturally implement
- Tests enforcing requirements from files REFERENCED by instruction.md (e.g.,
  report_requirements.md, design-spec.txt, prorules.txt, game_manual.txt,
  output-format.txt, format_and_outputs.md, nav-structure.json, config.json).
  These are DISCLOSED requirements, NOT hidden criteria.
- Tests with quantitative thresholds (percentages, counts, limits) that originate
  from referenced spec/requirements files — these are legitimate acceptance criteria

REFERENCED SPEC FILES — IMPORTANT RULE:
If instruction.md says "see report_requirements.md", "follow the spec in design-spec.txt",
"refer to prorules.txt", or otherwise points to another file as the source of requirements,
ALL requirements in that referenced file are considered DISCLOSED. Tests that enforce those
requirements are VALID and must NOT be flagged as undisclosed or hidden.

FILE NAMING — BE STRICT:
If instruction.md only specifies an OUTPUT DIRECTORY but tests require SPECIFIC FILENAMES:
-> FAIL: Filenames are NOT implied unless instruction.md or a referenced spec file mentions them.

ONLY FLAG AS FAIL IF:
1. Tests CONTRADICT the prompt
2. Tests check for ARBITRARY magic values with no logical basis
3. Tests use MODEL GATING
4. Tests directly execute solve.sh or import solution
5. Tests contain raw 'raise' statements (must use assert or pytest.fail)
6. Tests involve filesystem symlinks (not OS-agnostic)
7. Tests check for requirements IMPOSSIBLE to infer from instruction.md, its referenced files, or domain context
8. Tests require SPECIFIC FILENAMES not mentioned in instruction.md or any referenced spec file

PART 3: FORBIDDEN PATTERNS
- Model gating tests (checking model name to fail specific models)
- Tests that run solve.sh or import solution module
- Raw 'raise' statements inside test functions
- Symlink-based tests (not OS-agnostic)
- Hardcoded expected values model couldn't derive from instructions

PART 4: VACUOUS / ALWAYS-PASS ASSERTIONS (CRITICAL)
Tests that ALWAYS pass regardless of the implementation are worse than no tests.
FLAG IMMEDIATELY if found:
- "assert True" in else/fallback branches (passes even when check fails)
  Example: if match: assert match == expected else: assert True  <-- VACUOUS
- Test functions with only "pass" statement and no assertions at all
- Test bodies that are clearly incomplete/placeholder (comments like "TODO", "not finished")
- Assertions that are tautological: assert len(x) >= 0, assert True, assert 1 == 1
- Assertions that use overly broad conditions: assert isinstance(result, object)

WHY THIS IS CRITICAL: Vacuous assertions mean the test NEVER fails, so it provides
zero quality assurance. The client specifically flagged this as a major issue.

VERDICT: FAIL if any vacuous/always-pass assertion is found

PART 5: INCOMPLETE TEST IMPLEMENTATION (CRITICAL)
Check for tests that were NEVER FINISHED:
- Test functions with only a "pass" statement (no assertions)
- Test functions with placeholder comments indicating unfinished work
- Test functions that compute values but never assert anything
- Functions that end abruptly without any assertion after setup code

WHY THIS IS CRITICAL: Incomplete tests were specifically flagged by the client
as a P0 issue (email triage planner test with "pass" placeholder).

VERDICT: FAIL if any incomplete test function is found

PART 6: BRITTLE / WEAK TEST DETECTION
BRITTLE PATTERNS (FLAG AS WARNING):
- Checking if a short string/number appears ANYWHERE in combined output
- Using 'in' operator on large text blobs instead of parsing structured output
- Keyword presence checks that any trivial output could satisfy

VERDICT: WARNING if >50% of tests use brittle string matching

PART 7: REGEX-ONLY TESTING FOR VISUAL/UI TASKS
For tasks in frontend-development, ui-ux-optimization, or games-development:
If instruction.md specifies visual/interactive output (HTML, canvas, UI components),
tests MUST NOT rely solely on regex/string matching against source code.
- Regex matching on source code CANNOT verify rendering correctness
- Tests should use browser-based validation (Playwright, Puppeteer) or DOM assertions
- Checking TypeScript type annotations or class structures is NOT a rendering test
FLAG if: Tests only use regex/string pattern matching for a task that produces visual output
VERDICT: FAIL for visual tasks with regex-only tests

OUTPUT FORMAT (JSON):
{
  "score": "PASS" | "PASS_WITH_WARNING" | "FAIL",
  "docstrings": {"total_tests": 0, "good": 0, "missing_or_generic": [], "verdict": "..."},
  "humane_validation": {"contradicting_tests": [], "undisclosed_filenames": [], "verdict": "..."},
  "forbidden_patterns": {"model_gating": "...", "solve_access": "...", "raw_raise": "...", "symlinks": "...", "verdict": "..."},
  "brittle_tests": {"weak_tests": [], "verdict": "..."},
  "issues": [],
  "summary": "..."
}
"""


# ── QD-C: Slug & Naming ──────────────────────────────────────────────────

QD_C_RUBRIC = r"""
C) SLUG & NAMING (root folder)
Goal: Check ONLY whether the <slug> in the root folder name is descriptive for the instruction.md instruction.

This is ONLY a slug descriptiveness check.
- Does the slug describe the task's action/goal?
- Compare the slug against instruction.md content.
- That is ALL. No other checks.

DO NOT check or fail for:
- Folder naming conventions
- UUID presence or absence
- Folder format patterns

BAD SLUG EXAMPLES:
- data-analysis-task (generic/vague)
- utils (too short)
- final-project (meta/organizational)
- project-x (placeholder)
- use-python (names tool, not action)
- analyse (misspelled/overly terse)
- my-solution (author-centric)

GOOD SLUG EXAMPLES:
- detect-orphan-fk-records (specific action + target)
- parse-jsonl-sessionizer (clear action + format)
- train-sentiment-lstm-classifier (domain + method + target)
- sessionize-jsonl (action + format)

OUTPUT FORMAT (JSON):
{
  "score": "PASS" | "FAIL",
  "slug": "<extracted slug>",
  "task_goal": "<one sentence from instruction.md>",
  "reasoning": "...",
  "suggested_alternatives": [],
  "issues": [],
  "summary": "..."
}
"""


# ── QD-E: Dockerfile ─────────────────────────────────────────────────────

QD_E_RUBRIC = r"""
E) DOCKERFILE — HARBOR VERSION
Goal: Validate Dockerfile for Harbor tasks.

HARBOR STRUCTURE CONTEXT:
  task/
    environment/     <- Dockerfile is HERE, can only access files in this folder
    solution/        <- SEPARATE folder, Dockerfile CANNOT access this
    tests/           <- SEPARATE folder, Dockerfile CANNOT access this

PART 1: REFERENCE CHECK (Critical)
The Dockerfile MUST NOT contain:
- References to test files (test_outputs.py, test_state.py, test.sh)
- References to solution files (solve.sh, solution.py)
- Commands that execute tests (RUN pytest, RUN bash test.sh)
- Commands that execute solutions (RUN bash solve.sh)

PART 2: VERSION PINNING
CRITICAL: Pin pip packages, DO NOT pin apt packages.
- apt packages pinned -> FAIL (will break over time)
- pip packages not pinned -> WARNING

PART 3: TEST DEPENDENCIES IN IMAGE
Test deps (pytest, testing libs) should be in test.sh, NOT Dockerfile.
- pytest in Dockerfile -> WARNING

PART 4: BASE IMAGE & STRUCTURE
PASS: Standard TB base image, WORKDIR /app, copies only from environment/
WARNING: Non-standard base image (ubuntu, python:slim, etc.)
FAIL: Runs tests/solution, missing WORKDIR, empty/malformed, apt pinned

OUTPUT FORMAT (JSON):
{
  "score": "PASS" | "PASS_WITH_WARNING" | "FAIL",
  "reference_check": {"verdict": "...", "findings": []},
  "version_pinning": {"apt_pinned": [], "pip_unpinned": [], "verdict": "..."},
  "test_deps": {"found": [], "verdict": "..."},
  "base_image": {"name": "...", "standard": true, "workdir": true, "verdict": "..."},
  "issues": [],
  "summary": "..."
}
"""


# ── QD-F: test.sh ────────────────────────────────────────────────────────

DEFAULT_TEST_SH = r"""#!/bin/bash
apt-get update
apt-get install -y curl
curl -LsSf https://astral.sh/uv/0.9.7/install.sh | sh
source $HOME/.local/bin/env
uvx \
  --with pytest==8.4.1 \
  --with pytest-json-ctrf==0.3.5 \
  pytest --ctrf /logs/verifier/ctrf.json /tests/test_state.py -rA
if [ $? -eq 0 ]; then
  echo 1 > /logs/verifier/reward.txt
else
  echo 0 > /logs/verifier/reward.txt
fi
"""

QD_F_RUBRIC = r"""
F) test.sh
Goal: Check if test.sh matches the default reference or an acceptable variation.
Only adding packages/dependencies extra is allowed.

IMPORTANT - TEST FILE NAMING:
Both 'test_state.py' and 'test_outputs.py' are VALID test file names.
The test file name in test.sh MUST match the actual test file present in tests/.
- DO NOT flag if the name differs from default but matches actual file.
- ONLY flag if test.sh references a file that doesn't exist in tests/.

Also acceptable: uv venv .tbench-testing; source .tbench-testing/bin/activate; uv pip install pytest==8.4.1

CHECK FOR:
- Exact match with default: YES/NO
- If not exact, list material differences
- Forced failures or model gates
- Leaking answers or changing default flow
- Anything suspicious

OUTPUT FORMAT (JSON):
{
  "score": "PASS" | "PASS_WITH_WARNING" | "FAIL",
  "exact_match": true | false,
  "differences": [],
  "issues": [],
  "summary": "..."
}
"""


# ── QD-G: solve.sh ───────────────────────────────────────────────────────

QD_G_RUBRIC = r"""
G) solve.sh
Goal: Real, meaningful solution that corresponds to the prompt (a true Terminal-Bench task).

STRICT Requirements:
- MUST perform meaningful computation — not just print or copy answers
- MUST read inputs exactly as specified in instruction.md and write to specified locations
- MUST execute every operation described in instruction.md to derive the final answer
- Any auxiliary code generated MUST be executed; outputs must come from execution
- Commands should actually transform/process data
- Echo/printf allowed only for logging, NOT for directly writing final answers
- MUST NOT echo constants, cat/cp pre-made results, or hardcode outputs
- MUST align with instruction.md

RED FLAGS (examples that should cause FAIL):
- Solution logic depends on specific dataset structure or expected output values
- Conditional branches altering behavior for certain known inputs
- Manual corrections/offsets applied to align with pre-known outputs
- Static constants that don't come from input data
- Post-processing that exists only to shape results into expected format
- Script targets known files instead of performing general analysis (AUTHOR LEAKAGE)
- References Terminal-Bench harness variables (T_BENCH_TEST_DIR, TB_MODEL, etc.)
- Directly writing fixed answers (echo "42" > result.txt)
- Copying precomputed artifacts
- Generating code but NOT executing it
- Using placeholders or stubs
- Fabricating input data inside solve.sh when instruction says data is provided
- Using tools NOT listed in instruction.md constraints or Docker environment
- Non-deterministic outputs (timestamps, random data)

OUTPUT FORMAT (JSON):
{
  "score": "PASS" | "PASS_WITH_WARNING" | "FAIL",
  "computation": {"meaningful": true, "reasoning": "..."},
  "hardcoding": {"detected": false, "findings": []},
  "author_leakage": {"detected": false, "findings": []},
  "alignment": {"matches_instruction": true, "mismatches": []},
  "issues": [],
  "summary": "..."
}
"""


# ── QD-H: Task Metadata ─────────────────────────────────────────────────

QD_H_RUBRIC = r"""
H) TASK METADATA (task.toml)
Goal: Validate that task.toml contains all required metadata fields with valid values.

REQUIRED FIELDS:
1. version - Should be '1.0'
2. [metadata] section:
   - author_name: Non-empty (can be 'anonymous')
   - author_email: Non-empty (can be 'anonymous')
   - difficulty: One of 'easy', 'medium', 'hard'
   - category: Valid domain
   - tags: Array of relevant tags
3. [verifier] section:
   - timeout_sec: Positive number (typically 300-3600)
4. [agent] section:
   - timeout_sec: Positive number (typically 600-3600)
5. [environment] section:
   - build_timeout_sec: Positive number
   - cpus: Positive integer
   - Memory: EITHER memory_mb (int) OR memory (string like '2G')
   - Storage: EITHER storage_mb (int) OR storage (string like '10G')

VALIDATION CHECKS:
- difficulty should match task slug
- category should match task domain in slug

OUTPUT FORMAT (JSON):
{
  "score": "PASS" | "PASS_WITH_WARNING" | "FAIL",
  "missing_fields": [],
  "invalid_fields": [],
  "consistency": {"difficulty_match": true, "category_match": true},
  "issues": [],
  "summary": "..."
}
"""


# ── QD-J: Forced Gates ──────────────────────────────────────────────────

QD_J_RUBRIC = r"""
J) FORCED GATES — MODEL DETECTION & DELIBERATE FAILURE
Goal: Detect if tests or test.sh contain code that detects which model is running and deliberately fails it.

SEARCH FOR THESE PATTERNS in tests/test_outputs.py AND test.sh:

1. MODEL DETECTION VIA ENVIRONMENT VARIABLES:
   - os.environ.get('TB_MODEL'), os.getenv('MODEL'), os.getenv('OPENAI_MODEL')
   - $TB_MODEL, $MODEL, $OPENAI_MODEL in bash

2. MODEL NAME DETECTION FUNCTIONS:
   - _detect_model_name(), get_model_name(), detect_model()

3. BLOCK/ALLOW LISTS:
   - FAIL_MODELS = [...], BLOCKED_MODELS = [...]
   - if model in ['claude', 'hunyuan', ...]

4. CONDITIONAL FAILURES BASED ON MODEL:
   - if model == 'hunyuan': pytest.fail()

5. MODEL-SPECIFIC ASSERTIONS:
   - Different expected values for different models

WHY THIS IS MALPRACTICE:
Tests should evaluate the MODEL'S OUTPUT, not the model's IDENTITY.

OUTPUT FORMAT (JSON):
{
  "score": "PASS" | "FAIL",
  "model_detection": {"found": false, "patterns": []},
  "conditional_failures": {"found": false, "patterns": []},
  "block_lists": {"found": false, "patterns": []},
  "issues": [],
  "summary": "..."
}
"""


# ── QD-M: Instruction-Test Alignment ────────────────────────────────────

QD_M_RUBRIC = r"""
M) INSTRUCTION-TEST ALIGNMENT CHECK
Goal: Verify that all tests are justified and supported by instruction.md OR files it references.

IMPORTANT — REFERENCED SPEC FILES RULE:
If instruction.md references or points to another file (e.g., "see report_requirements.md",
"follow the spec in design-spec.txt", "refer to prorules.txt for rules"), then ALL requirements
in that referenced file count as DISCLOSED for alignment purposes. Tests that enforce those
requirements are VALID and must NOT be marked as undeclared/hidden.

Common referenced spec files include: report_requirements.md, design-spec.txt, prorules.txt,
game_manual.txt, output-format.txt, format_and_outputs.md, player_notes.md, config.json,
nav-structure.json, mockup.txt, table-config.json, and similar files in the task's src/ or
environment/ directories.

STAGE 0 — TEST FILE REFERENCE CHECK
If a test references a shared file (input data, config), instruction.md or a referenced spec
file MUST mention it. FAIL only if the file has zero connection to any disclosed document.

STAGE 1 — BIDIRECTIONAL COVERAGE & ALIGNMENT
1. Instruction -> Test Mapping (Forward):
   - Extract every requirement from instruction.md AND its referenced spec files
   - Find corresponding test assertion
   - Mark untested instructions

2. Test -> Instruction Mapping (Reverse):
   - Extract every test assertion
   - Verify instruction.md OR a referenced spec file provides the expectation
   - Mark undeclared test assertions ONLY if they cannot be traced to any disclosed file

3. Hidden/Misleading Test Detection:
   - Hardcoded filenames, constants, or function names absent in instruction.md AND all referenced files
   - Deep internal checks instead of output-level validation

   FILENAME SPECIFICITY:
   If instruction.md only specifies OUTPUT DIRECTORY but tests require SPECIFIC FILENAMES:
   Flag as UNDECLARED only if the filenames are also absent from any referenced spec file.

STAGE 2 — STRICT COVERAGE GAPS (CRITICAL)
1. NUMERIC VALUE ASSERTIONS:
   - Extract ALL numeric metrics from instruction.md
   - Verify tests assert ACTUAL VALUES, not just existence
   BAD: assert 'ORPHAN_COUNT' in summary (only checks key exists)
   GOOD: assert summary['ORPHAN_COUNT'] == expected_count

2. FORMATTING RULE ASSERTIONS:
   - Extract ALL formatting rules from instruction.md
   - Verify tests explicitly check EACH rule
   BAD: No test for trailing spaces when instruction says "no trailing spaces"

3. EXACT vs PARTIAL MATCHING:
   BAD: assert 'error_line' in issues_content (allows extra garbage)
   GOOD: assert issues_content.strip().split('\n') == expected_lines

4. BOUNDARY CONDITIONS:
   - If instruction specifies ranges/limits, tests should verify boundaries

5. BRITTLE / WEAK ASSERTIONS:
   BAD: assert '3' in (html + js_content) — trivially satisfiable
   GOOD: assert board['todo']['wip_limit'] == 3 — parses structure

STAGE 3 — TIERED EVALUATION (HUMANE PROMPT MODE)
CRITICAL (causes FAIL):
- Undisclosed output files with zero hints in instruction.md AND zero hints in any referenced spec file
- Secret validation rules not traceable to any disclosed document
- Tests requiring module/function names never mentioned in instruction.md or referenced files
- Untested numeric values, untested formatting rules, weak assertions

MINOR (note but PASS):
- Standard library conventions, JSON structure from examples
- File paths visible in Dockerfile
- Quantitative thresholds (80%, 85%, >=3, etc.) from referenced spec files — these are valid disclosed requirements
- Requirements originating from files explicitly referenced by instruction.md

OUTPUT FORMAT (JSON):
{
  "score": "PASS" | "PASS_WITH_WARNING" | "FAIL",
  "forward_coverage": {"untested_requirements": [], "incomplete": []},
  "reverse_coverage": {"undeclared_assertions": [], "hidden_tests": []},
  "coverage_gaps": {"untested_numeric": [], "untested_formatting": [], "weak_assertions": [], "missing_boundary": []},
  "critical_issues": [],
  "minor_notes": [],
  "issues": [],
  "summary": "..."
}
"""


# ── Registry of all QD checks ───────────────────────────────────────────

QD_REGISTRY: dict[str, dict] = {
    "A": {
        "name": "Instruction Quality",
        "rubric": QD_A_RUBRIC,
        "required_files": ["instruction_md", "dockerfile", "solve_sh"],
        "blocker": True,
    },
    "B": {
        "name": "Tests Quality",
        "rubric": QD_B_RUBRIC,
        "required_files": ["test_code", "instruction_md"],
        "blocker": True,
    },
    "C": {
        "name": "Slug & Naming",
        "rubric": QD_C_RUBRIC,
        "required_files": ["instruction_md"],
        "blocker": False,
    },
    "E": {
        "name": "Dockerfile",
        "rubric": QD_E_RUBRIC,
        "required_files": ["dockerfile"],
        "blocker": True,
    },
    "F": {
        "name": "test.sh",
        "rubric": QD_F_RUBRIC,
        "required_files": ["test_sh"],
        "blocker": False,
    },
    "G": {
        "name": "solve.sh",
        "rubric": QD_G_RUBRIC,
        "required_files": ["solve_sh", "instruction_md"],
        "blocker": True,
    },
    "H": {
        "name": "Task Metadata",
        "rubric": QD_H_RUBRIC,
        "required_files": ["task_toml_raw"],
        "blocker": False,
    },
    "J": {
        "name": "Forced Gates",
        "rubric": QD_J_RUBRIC,
        "required_files": ["test_code"],
        "blocker": True,
    },
    "M": {
        "name": "Instruction-Test Alignment",
        "rubric": QD_M_RUBRIC,
        "required_files": ["instruction_md", "test_code"],
        "blocker": True,
    },
}


def _format_env_contents(task: dict, max_total: int = 60_000) -> str:
    """Format environment file contents for inclusion in QD prompts (--msource)."""
    contents = task.get("env_file_contents", [])
    if not contents or not task.get("_msource"):
        return ""
    lines = ["\n--- ENVIRONMENT FILE CONTENTS (--msource deep review) ---"]
    total = 0
    for ef in contents:
        if total >= max_total:
            lines.append(f"(remaining files truncated at {max_total} chars)")
            break
        budget = max_total - total
        text = ef["content"]
        if len(text) > budget:
            text = text[:budget] + "\n... (truncated)"
        lines.append(f"\n--- environment/{ef['name']} ({ef['size']} bytes) ---")
        lines.append(text)
        total += len(text)
    return "\n".join(lines)


def build_qd_user_content(qd_id: str, task: dict) -> str:
    """Build the user content section for a specific QD check."""

    instruction = task.get("instruction_md") or "(missing)"
    test_code = task.get("test_code") or "(missing)"
    solve_sh = task.get("solve_sh") or "(missing)"
    dockerfile = task.get("dockerfile") or "(missing)"
    test_sh = task.get("test_sh") or "(missing)"
    task_toml = task.get("task_toml_raw") or "(missing)"
    folder_name = task.get("folder_name", "(unknown)")
    slug = task.get("slug", "(unknown)")

    env_files = task.get("env_files", [])
    env_formatted = "\n".join(f"- {f}" for f in env_files) if env_files else "(no environment files)"
    env_contents = _format_env_contents(task)

    if qd_id == "A":
        base = (
            f"--- instruction.md ---\n{instruction}\n\n"
            f"--- ENVIRONMENT FILES (in environment/ folder) ---\n{env_formatted}\n\n"
            f"--- Dockerfile ---\n{dockerfile}\n\n"
            f"--- solve.sh ---\n{solve_sh}"
        )
        if env_contents:
            base += (
                f"\n\n{env_contents}\n\n"
                "MSOURCE: Cross-check that data files above match what "
                "instruction.md describes (column names, schemas, values, formats)."
            )
        return base

    if qd_id == "B":
        base = (
            f"FILES:\n--- instruction.md ---\n{instruction}\n\n"
            f"--- tests/{task.get('test_filename', 'test_outputs.py')} ---\n{test_code}"
        )
        if env_contents:
            base += (
                f"\n\n{env_contents}\n\n"
                "MSOURCE: Verify that hardcoded expected values in tests are "
                "derivable from the environment data above. Flag any magic values "
                "that cannot be traced to these source files."
            )
        return base

    if qd_id == "C":
        return (
            f"FILES:\n--- root-folder-name ---\n{folder_name}\n\n"
            f"--- instruction.md ---\n{instruction}"
        )

    if qd_id == "E":
        base = (
            f"FILE: Dockerfile\n----------------\n{dockerfile}\n\n"
            f"Context (environment files):\n{env_formatted}\n\n"
            f"FILE: instruction.md\n{instruction}"
        )
        if env_contents:
            base += (
                f"\n\n{env_contents}\n\n"
                "MSOURCE: Verify that Dockerfile COPY commands cover all "
                "environment files needed by the task."
            )
        return base

    if qd_id == "F":
        test_filename = task.get("test_filename", "test_outputs.py")
        return (
            f"FILES:\n--- test.sh (actual) ---\n{test_sh}\n\n"
            f"--- test.sh (DEFAULT reference) ---\n{DEFAULT_TEST_SH}\n\n"
            f"--- tests directory files ---\n"
            f"- {test_filename}"
        )

    if qd_id == "G":
        return (
            f"FILES:\n--- instruction.md ---\n{instruction}\n\n"
            f"--- solve.sh ---\n{solve_sh}\n\n"
            f"--- Dockerfile content ---\n{dockerfile}"
        )

    if qd_id == "H":
        return f"TASK SLUG: {slug}\n\n--- task.toml ---\n{task_toml}"

    if qd_id == "J":
        return (
            f"FILES:\n--- tests/{task.get('test_filename', 'test_outputs.py')} ---\n{test_code}\n\n"
            f"--- test.sh ---\n{test_sh}"
        )

    if qd_id == "M":
        base = (
            f"FILES:\n--- instruction.md ---\n{instruction}\n\n"
            f"--- tests/{task.get('test_filename', 'test_outputs.py')} ---\n{test_code}"
        )
        if env_contents:
            base += (
                f"\n\n{env_contents}\n\n"
                "MSOURCE: With actual environment data available, perform deeper "
                "alignment checks:\n"
                "- Are test expected values consistent with the actual input data?\n"
                "- Do instruction claims about data properties (row count, columns, "
                "value ranges) match reality?\n"
                "- Are there hidden data dependencies that tests rely on but "
                "instruction.md doesn't mention?"
            )
        return base

    return f"(Unknown QD: {qd_id})"
